line_length: 160

excluded:
  - Pods
  - MovieGrid/Resources/R

disabled_rules:
  - file_length
  - force_cast
  - identifier_name
  - type_name
  - function_body_length
  - nesting
  - cyclomatic_complexity
  - type_body_length
  - generic_type_name
  - shorthand_operator
